apiVersion: v1
kind: Namespace
metadata:
   name: monitoring
   annotations:
      argocd.argoproj.io/sunc-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"